name: Slack Notification on Failure

on:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed

jobs:
  notify-slack-on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "워크플로우 실행 실패 :x:",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*워크플로우 실행 실패* ⚠️\n\n*저장소:* ${{ github.repository }}\n*워크플로우:* ${{ github.event.workflow_run.name }}\n*결과:* ${{ github.event.workflow_run.conclusion }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "실패한 워크플로우 확인"
                      },
                      "url": "${{ github.event.workflow_run.html_url }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
